# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0004_delete_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CostsTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('money', models.IntegerField()),
                ('costs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.Costs')),
            ],
        ),
        migrations.CreateModel(
            name='FundsTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('money', models.IntegerField()),
                ('funds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.Funds')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Neto',
        ),
        migrations.AddField(
            model_name='worker',
            name='workerlist',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='v0.WorkerList'),
            preserve_default=False,
        ),
    ]
