# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=32)),
                ('prezime', models.CharField(max_length=32)),
                ('plata', models.IntegerField()),
                ('stanje', models.CharField(default='Active', max_length=32)),
            ],
        ),
    ]
