# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0003_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
