# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0005_auto_20160521_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='funds',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
